@startuml CA
skinparam handwritten true

Client -> Server: create project
Client -> Server: create CA Pool
Client -> Server: create root CA
Client -> Server: create sobordinate CA
Client -> Server: create server certficate
Client -> Server: get server certficate

== certificate ==
Client -> Server: renewal
Client -> Server: revoke

@enduml